hopfarm-limit-fix:
      config: {}
    ai-ox-tethers:
      config: {}
    workers:
      config: {}
  plugins:
    StrongholdEurope:
      config: {}
    Ascension-AI-Tournament:
      config: {}
    Ascension-Balance:
      config: {}
    Mod-KI-Team-Liga:
      config: {}
    KIPaketLordPhoenix:
      config: {}
  load-order:
    
extension: citizens
version: 1.0.0
extension: workers
version: 0.0.1
extension: ai-ox-tethers
version: 1.0.3
extension: hopfarm-limit-fix
version: 0.1.2
extension: Ascension-Balance
version: 1.1.4
meta:
  version: 1.0.0